Tso implementation
idmp-fences/toylang pull request #4
Opened 2024-05-23 18:19 UTC by killB0x

2024-05-23 18:50 UTC, boerdereinar requested changes

2024-05-23 18:50 UTC, boerdereinar commented on interpreter/src/lib.rs
> +            }
This is incorrect. The write buffer should follow FIFO ordering to preserve WW ordering in TSO.

2024-05-23 18:50 UTC, boerdereinar commented on interpreter/src/lib.rs
> +        }
No special logic should be needed here since reads should just read from the current memory and especially not from the write buffers.

2024-05-23 18:50 UTC, boerdereinar commented on interpreter/src/lib.rs
> +                    }
Don't read from the write buffers

2024-05-23 18:50 UTC, boerdereinar commented on interpreter/src/lib.rs
> +        }
I don't think local variables need to interact with the write buffers since they mainly act as intermediate values and are not present in the aeg

2024-05-23 18:50 UTC, boerdereinar commented on interpreter/src/lib.rs
> +                }
This should always insert the value into the write buffer and never directly into memory

2024-05-23 18:50 UTC, boerdereinar commented on interpreter/src/lib.rs
> +                state.flush_write_buffer(&threads[thread_idx].name);
I don't think the write buffer should be immediately flushed after the thread finishes since it prevents for some inter-leavings to occur

2024-05-23 18:50 UTC, boerdereinar commented on interpreter/src/lib.rs
> +fn assert(assert: &[LogicExpr], state: &mut State) {
Assert shouldn't have `mut` here since it shouldn't mutate memory in any way

2024-05-24 09:30 UTC, killB0x commented
Thank you for the feedback. I applied all the recommended changes. Let me know if there is something else I should change, or if there are other tests I should add, that might be relevant.

2024-05-24 10:36 UTC, boerdereinar commented on interpreter/src/lib.rs
>      fn test_thread_end() {
For this test you might want to introduce a seeded RNG to make it deterministic. The rest of the code looks fine now.

2024-05-27 13:46 UTC, merged