Ifs and loops + test programs
idmp-fences/toylang pull request #8
Opened 2024-06-04 10:48 UTC by boerdereinar

Adds if statements and while loops to the parser, aeg and interpreter. Also adds a few test programs.

2024-06-04 11:41 UTC, lucasvanmol commented on programs/peterson-sc.toy
Getting some parsing errors trying to run this one and `peterson-tso.toy`
```
cargo run -p toy -- -i .\programs\peterson-sc.toy
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `target\debug\toy.exe -i .\programs\peterson-sc.toy`
thread 'main' panicked at src\main.rs:43:42:
called `Result::unwrap()` on an `Err` value: Error { variant: ParsingError { positives: [logicatom], negatives: [] }, location: Pos(121), line_col: Pos((8, 26)), path: None, line: "    while (!(y == 0) && (turn == 0)) { }", continued_line: None, parse_attempts: None }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\toy.exe -i .\programs\peterson-sc.toy` (exit code: 101)
```

2024-06-04 11:52 UTC, lucasvanmol commented
The if & while implementation looks really nice but I have some comments:
- I'm trying to run the `-sc` programs with `-m tso` but not getting any failed assertions, is that normal? Probably more of an issue with the interpreter?
- I think it would be good to add some tests to the aeg modules including ifs and whiles, and see that it generates the proper structure and critical cycles, something similar to fig 9 and 10 of the paper could be a good start, but we could also make more complicated examples
![image](https://github.com/idmp-fences/toylang/assets/16979353/0d9bdb9e-e40d-43cd-8e95-7fa12b090ca9)

2024-06-04 12:54 UTC, lucasvanmol requested changes

2024-06-04 12:54 UTC, lucasvanmol commented on aeg/src/aeg.rs
Here is the test I mentioned in a previous comment, unfortunately it fails so that needs to be fixed. Also need to add a test for while statements

```rs
#[test]
fn ifs() {
    // Fig 9. and 10. of Don't Sit on the Fence
    let program = r#"
    let x: u32 = 0;
    let y: u32 = 0;
    let z: u32 = 0;
    thread t1 {
        let a: u32 = 0;
        x = 42;
        if (1 == 1) {
            y = 1;
        } else {
            a = z;
        }
        x = 1;
    }
    thread t2 {
        let b: u32 = y;
        let c: u32 = z;
        let d: u32 = x;
    }
    final {}
    "#;

    let program = parser::parse(program).unwrap();

    let aeg = create_aeg(&program);
    dbg!(Dot::with_config(&aeg, &[]));

    assert_eq!(aeg.node_count(), 7);

    assert_eq!(
        aeg.edge_references()
            .filter(|e| matches!(e.weight(), AegEdge::ProgramOrder))
            .count(),
        6
    );

    assert_eq!(
        aeg.edge_references()
            .filter(|e| matches!(e.weight(), AegEdge::Competing))
            .count(),
        3 * 2 // doubled because cmp edges are undirected
    );

    // find the t1 nodes
    let mut wx1 = None;
    let mut wx2 = None;
    let mut wy = None;
    let mut rz = None;
    for (id, node) in aeg.node_references() {
        match node {
            Node::Write(thread, addr) => {
                if thread.as_str() == "t1" {
                    if addr.as_str() == "y" {
                        wy = Some(id)
                    } else if addr.as_str() == "x" {
                        if wx1.is_none() {
                            wx1 = Some(id)
                        } else if wx2.is_none() {
                            wx2 = Some(id)
                        } else {
                            panic!()
                        }
                    } else {
                        panic!()
                    }
                }
            }
            Node::Read(thread, addr) => {
                if thread.as_str() == "t1" {
                    if addr.as_str() == "z" {
                        rz = Some(id)
                    } else {
                        panic!()
                    }
                }
            }
            _ => {}
        }
    }

    let wx1: NodeIndex = wx1.unwrap();
    let wx2: NodeIndex = wx2.unwrap();
    let wy: NodeIndex = wy.unwrap();
    let rz: NodeIndex = rz.unwrap();

    // ensure we have the correct structure
    assert!(aeg.contains_edge(wx1, wy));
    assert!(aeg.contains_edge(wx1, rz));
    assert!(aeg.contains_edge(wy, wx2));
    assert!(aeg.contains_edge(rz, wx2));
}
```

2024-06-04 12:56 UTC, lucasvanmol commented on aeg/src/aeg.rs
Some critical cycle tests could also be helpful in `critical_cycles.rs` - mainly to check the functionality of searching the transitive edges, because I don't know how that's going to work for while loops.

2024-06-05 15:46 UTC, lucasvanmol commented on src/main.rs
> +    if !args.parse_only { return; }
The `!` needs to be removed here.

2024-06-05 20:41 UTC, boerdereinar commented
> The if & while implementation looks really nice but I have some comments:
> 
>     * I'm trying to run the `-sc` programs with `-m tso` but not getting any failed assertions, is that normal? Probably more of an issue with the interpreter?
> 
>     * I think it would be good to add some tests to the aeg modules including ifs and whiles, and see that it generates the proper structure and critical cycles, something similar to fig 9 and 10 of the paper could be a good start, but we could also make more complicated examples
>       ![image](https://private-user-images.githubusercontent.com/16979353/336435143-0d9bdb9e-e40d-43cd-8e95-7fa12b090ca9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTA0MDIsIm5iZiI6MTcxNzYxMDEwMiwicGF0aCI6Ii8xNjk3OTM1My8zMzY0MzUxNDMtMGQ5YmRiOWUtZTQwZC00M2NkLThlOTUtN2ZhMTJiMDkwY2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE3NTUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzZGIwYzEzMDc4Mjc5YzVkNjY0NTBjZmRiMjk2YTgzOTBkZGQ5OGVhZmM5OTA4MTJjYjUwOWQ2MWIzNzU5ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pon-2b44jYSe8pcLFBuXQaxFyI5bEUS74eyvCc_1lV0)

1. Yeah, most programs don't contain any assertions so there's nothing to fail.
2. I added some test (and discovered some bugs with the while implementation)

2024-06-05 20:49 UTC, boerdereinar commented on aeg/src/aeg.rs
There shouldn't be any problems with fence placement in the while loops. The main problem would be the conditions not supporting fence placement between reads in the toy language, but that is all just a problem for the toy language definition.

2024-06-06 11:18 UTC, lucasvanmol commented
looks good, I added in some tests for critical cycles but unfortunately I'm getting a stack overflow on programs with while loops - I'll take a closer look this afternoon or tomorrow

2024-06-07 13:38 UTC, merged